-- ============================================================================
-- GreenShoes Database Migration - Initial Schema
-- Developer: Kamalasankari Subramaniakuppusamy
-- Generated by: Prisma Migrate
-- ============================================================================
--
-- This migration creates the complete database schema for the GreenShoes
-- luxury eco-friendly footwear e-commerce platform.
--
-- REQUIREMENTS COVERED:
-- - User registration and login functionality (User table)
-- - Different Admin login vs customer login (UserRole enum with CUSTOMER/ADMIN)
-- - Add items with multiple pictures (Product + ProductImage tables)
-- - Add/modify quantities per size and color (ProductVariant table)
-- - Place items on sale (Product.onSale + Product.salePrice fields)
-- - Display unique confirmation ID per order (Order.id as TEXT/UUID)
-- - Display order ID, color, size, addresses, total (Order + OrderItem + Address)
-- - Shopping cart functionality (CartItem table with guest session support)
-- - Wishlist functionality (WishlistItem table)
-- - Impact/sustainability storytelling (Product.impactText, impactScore, impactVideoUrl)
--
-- ============================================================================


-- ============================================================================
-- ENUMS
-- Using PostgreSQL native enums for type safety - better than just strings
-- ============================================================================

-- CreateEnum
-- REQUIREMENT: "Different Admin login URL and customer login to prevent break-in attacks"
-- Role-based access control - CUSTOMER is default, ADMIN gets access to admin panel
CREATE TYPE "UserRole" AS ENUM ('CUSTOMER', 'ADMIN');

-- CreateEnum
-- Order lifecycle states - pretty standard e-commerce flow
-- PENDING = just created, PAID = payment confirmed, SHIPPED = on the way,
-- DELIVERED = customer got it, CANCELLED = something went wrong
-- Note: No REFUNDED status because requirement says "No returns or refunds"
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED');


-- ============================================================================
-- USER & AUTHENTICATION TABLES
-- ============================================================================

-- CreateTable
-- Core user table - both customers and admins live here
-- REQUIREMENT: "The software shall provide user registration and login functionality"
CREATE TABLE "User" (
    "id" TEXT NOT NULL,                                    -- UUID, not auto-increment (more secure)
    "email" TEXT NOT NULL,                                 -- Login identifier, must be unique
    "password" TEXT NOT NULL,                              -- Hashed with bcrypt, never plain text!
    "fullName" TEXT NOT NULL,                              -- Display name for orders, emails, etc.
    "role" "UserRole" NOT NULL DEFAULT 'CUSTOMER',         -- CUSTOMER or ADMIN - controls access
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,                     -- Prisma auto-updates this
    "billingAddressId" TEXT,                               -- Optional default billing address

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Two-factor authentication secrets - one per user
-- Nice security feature for protecting accounts, especially admin accounts
CREATE TABLE "TwoFactorSecret" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,                                -- One-to-one with User
    "secret" TEXT NOT NULL,                                -- The TOTP secret (encrypted ideally)
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TwoFactorSecret_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- ADDRESS TABLE
-- Shared by shipping and billing - users can have multiple addresses
-- ============================================================================

-- CreateTable
-- REQUIREMENT: "Display order ID, color, size, addresses, total"
-- Addresses are separate entities so users can save multiple and reuse them
CREATE TABLE "Address" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,                                -- Who owns this address
    "line1" TEXT NOT NULL,                                 -- Street address
    "line2" TEXT,                                          -- Apt/Suite number (optional)
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "postalCode" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,            -- Quick checkout uses this one

    CONSTRAINT "Address_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- PRODUCT TABLES
-- Core catalog: products, images, and size/color variants
-- ============================================================================

-- CreateTable
-- REQUIREMENT: "Add items with multiple pictures"
-- REQUIREMENT: "Change prices" and "Place items on sale"
-- Main product entity - variants handle the size/color combos
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,                                  -- e.g., "Ocean Wave Sandal"
    "description" TEXT NOT NULL,                           -- Full product description
    "price" DOUBLE PRECISION NOT NULL,                     -- Base selling price (this is selling_price in admin)
    "onSale" BOOLEAN NOT NULL DEFAULT false,               -- Toggle for sale status
    "salePrice" DOUBLE PRECISION,                          -- Discounted price when onSale=true
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    -- Impact/sustainability fields - luxury eco-friendly branding
    -- REQUIREMENT: "Impact management" (admin can edit these via product description)
    "impactText" TEXT,                                     -- Sustainability story for this product
    "impactScore" DOUBLE PRECISION,                        -- Environmental impact rating
    "impactVideoUrl" TEXT,                                 -- Video showing the eco impact

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- REQUIREMENT: "Add items with multiple pictures"
-- Separate table allows unlimited images per product
CREATE TABLE "ProductImage" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,                             -- Which product this belongs to
    "url" TEXT NOT NULL,                                   -- Image URL (S3, Cloudinary, etc.)

    CONSTRAINT "ProductImage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- REQUIREMENT: "Add/modify quantities per size and color"
-- REQUIREMENT: "Update inventory real-time"
-- REQUIREMENT: "Inventory can never be negative"
-- This is the magic table - each size/color combo is its own variant with stock
CREATE TABLE "ProductVariant" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,                             -- Parent product
    "size" TEXT NOT NULL,                                  -- e.g., "7", "8.5", "10"
    "color" TEXT NOT NULL,                                 -- e.g., "Ocean Blue", "Sand Beige"
    "stock" INTEGER NOT NULL DEFAULT 0,                    -- Current inventory count (min 0)

    CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- WISHLIST TABLE
-- Customers can save products they want to buy later
-- ============================================================================

-- CreateTable
-- Nice-to-have feature - helps with conversion when users come back
CREATE TABLE "WishlistItem" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,                                -- Who wishlisted it
    "productId" TEXT NOT NULL,                             -- What product they want

    CONSTRAINT "WishlistItem_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- SHOPPING CART TABLE
-- Supports both logged-in users and guest checkout
-- ============================================================================

-- CreateTable
-- Cart items link to specific variants (size + color matters!)
-- Guest checkout supported via guestSessionId - cart survives without login
CREATE TABLE "CartItem" (
    "id" TEXT NOT NULL,
    "userId" TEXT,                                         -- NULL for guest carts
    "guestSessionId" TEXT,                                 -- Session ID for guests
    "variantId" TEXT NOT NULL,                             -- Specific size/color combo
    "quantity" INTEGER NOT NULL DEFAULT 1,                 -- How many they want
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CartItem_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- ORDER TABLES
-- Completed purchases with line items
-- ============================================================================

-- CreateTable
-- REQUIREMENT: "Display unique confirmation ID per order"
-- REQUIREMENT: "Display order ID, color, size, addresses, total"
-- REQUIREMENT: "No returns or refunds" (hence no refund status or endpoints)
CREATE TABLE "Order" (
    "id" TEXT NOT NULL,                                    -- This IS the unique confirmation ID
    "userId" TEXT NOT NULL,                                -- Who placed the order
    "status" "OrderStatus" NOT NULL DEFAULT 'PENDING',     -- Current order state
    "totalAmount" DOUBLE PRECISION NOT NULL,               -- Final total including tax & shipping
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "shippingAddressId" TEXT NOT NULL,                     -- Where to ship it
    "billingAddressId" TEXT NOT NULL,                      -- Where to charge

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Line items for each order - captures the variant, quantity, and price at time of purchase
-- Price is stored here because product prices can change later - gotta snapshot it
CREATE TABLE "OrderItem" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,                               -- Parent order
    "variantId" TEXT NOT NULL,                             -- Which size/color was ordered
    "quantity" INTEGER NOT NULL,                           -- How many
    "price" DOUBLE PRECISION NOT NULL,                     -- Price at time of purchase (important!)

    CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id")
);


-- ============================================================================
-- INDEXES
-- Performance optimization for common queries
-- ============================================================================

-- CreateIndex
-- Email must be unique - it's the login identifier
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
-- One default billing address per user
CREATE UNIQUE INDEX "User_billingAddressId_key" ON "User"("billingAddressId");

-- CreateIndex
-- One 2FA secret per user (one-to-one relationship)
CREATE UNIQUE INDEX "TwoFactorSecret_userId_key" ON "TwoFactorSecret"("userId");

-- CreateIndex
-- REQUIREMENT: "Add/modify quantities per size and color"
-- Each product can only have ONE variant for each size+color combo
-- This prevents duplicate variants like two "Size 8, Blue" entries
CREATE UNIQUE INDEX "ProductVariant_productId_size_color_key" ON "ProductVariant"("productId", "size", "color");

-- CreateIndex
-- A user can only wishlist a product once (no duplicates)
CREATE UNIQUE INDEX "WishlistItem_userId_productId_key" ON "WishlistItem"("userId", "productId");

-- CreateIndex
-- Speed up guest cart lookups - happens on every page load for guests
CREATE INDEX "CartItem_guestSessionId_idx" ON "CartItem"("guestSessionId");

-- CreateIndex
-- A user can only have one cart entry per variant
-- Adding same item again should increase quantity, not create duplicate row
CREATE UNIQUE INDEX "CartItem_userId_variantId_key" ON "CartItem"("userId", "variantId");


-- ============================================================================
-- FOREIGN KEY CONSTRAINTS
-- Referential integrity - keeps the data consistent
-- ============================================================================

-- AddForeignKey
-- User's default billing address (optional, hence SET NULL on delete)
ALTER TABLE "User" ADD CONSTRAINT "User_billingAddressId_fkey" FOREIGN KEY ("billingAddressId") REFERENCES "Address"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
-- 2FA secret belongs to exactly one user
ALTER TABLE "TwoFactorSecret" ADD CONSTRAINT "TwoFactorSecret_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Addresses belong to users - can't delete user if they have addresses (RESTRICT)
ALTER TABLE "Address" ADD CONSTRAINT "Address_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Product images belong to products
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Variants belong to products - can't delete product if variants exist
ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Wishlist items reference users and products
ALTER TABLE "WishlistItem" ADD CONSTRAINT "WishlistItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WishlistItem" ADD CONSTRAINT "WishlistItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Cart items: user is optional (guest carts), variant is required
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Orders: user, shipping address, and billing address are all required
ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_shippingAddressId_fkey" FOREIGN KEY ("shippingAddressId") REFERENCES "Address"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_billingAddressId_fkey" FOREIGN KEY ("billingAddressId") REFERENCES "Address"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Order items reference their parent order and the variant purchased
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ============================================================================
-- SCHEMA NOTES
-- ============================================================================
--
-- Key Design Decisions:
--
-- 1. TEXT IDs instead of SERIAL/INT
--    - UUIDs are harder to guess (security)
--    - No sequential patterns to exploit
--    - Works better with distributed systems
--
-- 2. ProductVariant for size/color combos
--    - Each combo has its own stock count
--    - Unique constraint prevents duplicates
--    - CartItem and OrderItem reference variants, not products
--
-- 3. Price stored in OrderItem
--    - Captures price at time of purchase
--    - Product prices can change later without affecting old orders
--
-- 4. Guest cart support
--    - CartItem.userId is nullable
--    - guestSessionId tracks anonymous carts
--    - Cart can be "claimed" on login by updating userId
--
-- 5. ON DELETE RESTRICT everywhere important
--    - Prevents orphaned records
--    - Forces explicit cleanup before deletion
--    - Safer for e-commerce data integrity
--
-- ============================================================================